---
-
   name: Sending IOS commands
   hosts: all
   gather_facts: no

   tasks:
   - name: Sending a few simple Cisco IOS commands
      cisco.ios.ios_command:
          commands:
                - show version
                - show ip interface brief
      register: output
    - debug: var = output.stdout_lines
